package com.salad.cloud.sdk.models;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonProperty;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import lombok.ToString;
import lombok.With;
import lombok.extern.jackson.Jacksonized;
import org.openapitools.jackson.nullable.JsonNullable;

/**
 * Represents an API error
 */
@Data
@Builder
@With
@ToString
@EqualsAndHashCode
@Jacksonized
@NoArgsConstructor
@AllArgsConstructor
public class ProblemDetails {

  /**
   * The URI reference that identifies the error type.
   */
  @JsonProperty("type")
  private JsonNullable<String> type;

  /**
   * The short, human-readable summary of the error type.
   */
  @JsonProperty("title")
  private JsonNullable<String> title;

  /**
   * The HTTP status code generated by the origin server for this occurrence of the error.
   */
  @JsonProperty("status")
  private JsonNullable<Long> status;

  /**
   * The human-readable explanation specific to this occurrence of the error.
   */
  @JsonProperty("detail")
  private JsonNullable<String> detail;

  /**
   * The URI reference that identifies the specific occurrence of the error.
   */
  @JsonProperty("instance")
  private JsonNullable<String> instance;

  @JsonIgnore
  public String getType() {
    return type.orElse(null);
  }

  @JsonIgnore
  public String getTitle() {
    return title.orElse(null);
  }

  @JsonIgnore
  public Long getStatus() {
    return status.orElse(null);
  }

  @JsonIgnore
  public String getDetail() {
    return detail.orElse(null);
  }

  @JsonIgnore
  public String getInstance() {
    return instance.orElse(null);
  }

  // Overwrite lombok builder methods
  public static class ProblemDetailsBuilder {

    private JsonNullable<String> type = JsonNullable.of("about:blank");

    @JsonProperty("type")
    public ProblemDetailsBuilder type(String value) {
      if (value == null) {
        throw new IllegalStateException("type cannot be null");
      }
      this.type = JsonNullable.of(value);
      return this;
    }

    private JsonNullable<String> title = JsonNullable.undefined();

    @JsonProperty("title")
    public ProblemDetailsBuilder title(String value) {
      if (value == null) {
        throw new IllegalStateException("title cannot be null");
      }
      this.title = JsonNullable.of(value);
      return this;
    }

    private JsonNullable<Long> status = JsonNullable.undefined();

    @JsonProperty("status")
    public ProblemDetailsBuilder status(Long value) {
      if (value == null) {
        throw new IllegalStateException("status cannot be null");
      }
      this.status = JsonNullable.of(value);
      return this;
    }

    private JsonNullable<String> detail = JsonNullable.undefined();

    @JsonProperty("detail")
    public ProblemDetailsBuilder detail(String value) {
      if (value == null) {
        throw new IllegalStateException("detail cannot be null");
      }
      this.detail = JsonNullable.of(value);
      return this;
    }

    private JsonNullable<String> instance = JsonNullable.undefined();

    @JsonProperty("instance")
    public ProblemDetailsBuilder instance(String value) {
      if (value == null) {
        throw new IllegalStateException("instance cannot be null");
      }
      this.instance = JsonNullable.of(value);
      return this;
    }
  }
}
